before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: KcCPyTkN2XCcs89DwW7dG9xTMjfJEnaJxvrTWu6erq43WW7vnpIu8SBK/MfRuhWo6b1+/PH3GLxdi9FAzO8F+nFJlw3ICT9veaSol6u0mg+841ML+er9u7ctJEzKbblIGGFbtULHEOmJ0Xp+51BXrkns883UvpSZczrdxL6F2Ka8r0OVBQiGij/9WdTDUlgJTL/yK/mWDsqwjnj2aVbztmSzx97EHq9+LJVqDcdXDuoJP/e9M1NQoKpdb9sCO22brkHNllJipZ/WrmPe9qJYa7vJwLEnZlSvl8PgeODRKOt38ij1337ZjIgr2ItoPvx63ZFB9kr/HIE4qRpZCZ4GnJs4RRxteomw00yCGpxxVsAsCaj4RXu0qcpJy+eK+PJaDbkfwC3pWpVS98Wc9LT80SqeMu13+/T24SNWFTz0pLp0RDTJjB4Zj8Z6Le2SrfPFoy8oooxLF2+pi0Ro83uCMhl3SuoiT3SGgPaA5s/W78LZxk47GxZjDr7HfXJJwrxxvhFXLolufJT5u8a77K+u0/Q+6HrE9kfj3eEWhlymdNVF4G0xJOLbxz5bsB98zAVlcErHxE50ij+DfWJUCx65gvgbhFVkRdqlQMA1n776TgvQmFECkHhAhRd9qWyEjVzLXDyqbsjC2FRJLDnNPUCoMMloD6eCkQbmz9MLZnWBnFo= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
